apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "41"
data:
  config.yaml: |
{{ .Values.litellm.config | indent 4 }}
