{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-postgres-storage
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "41"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
{{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName }}
{{- end }}
{{- end }}
